// Code generated by protoapi:go; DO NOT EDIT.

package searchsvr

// SearchError
type SearchError struct {
	Req   *SearchReq `json:"req"`
	Error string     `json:"error"`
}

func (r *SearchError) GetReq() *SearchReq {
	if r == nil {
		var zeroVal *SearchReq
		return zeroVal
	}
	return r.Req
}

func (r *SearchError) GetError() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Error
}
