// Code generated by protoapi:go; DO NOT EDIT.

package searchsvr

// SearchReq
type SearchReq struct {
	UserId int `json:"userId"`
}

func (r *SearchReq) GetUserId() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.UserId
}
