// Code generated by protoapi:go; DO NOT EDIT.

package searchsvr

// SearchResponse
type SearchResponse struct {
	UserId    int    `json:"userId"`
	Id        int    `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

func (r *SearchResponse) GetUserId() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.UserId
}

func (r *SearchResponse) GetId() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Id
}

func (r *SearchResponse) GetTitle() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Title
}

func (r *SearchResponse) GetCompleted() bool {
	if r == nil {
		var zeroVal bool
		return zeroVal
	}
	return r.Completed
}
